/*$file${../../::main.c} ###################################################*/
/*
* Model: refrsher.qm
* File:  ${../../::main.c}
*
* This code has been generated by QM tool (https://state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${../../::main.c} ################################################*/
#include "qpn.h"    /* QP-nano framework API */
#include "rc5process.h"    /* Board Support Package interface */
#include "refresher.h"

/* Local-scope objects -----------------------------------------------------*/
static QEvt l_rc5processQSto[5]; /* Event queue storage for RC5 */
static QEvt l_refresherQSto[10];

/* QF_active[] array defines all active object control blocks --------------*/
QActiveCB const Q_ROM QF_active[] = {
    { (QActive *)0,               (QEvt *)0,         0U                       },
    { (QActive *)&AO_Refresher,   l_refresherQSto,   Q_DIM(l_refresherQSto)   },
    { (QActive *)&AO_RC5Process,  l_rc5processQSto,  Q_DIM(l_rc5processQSto)  }
};

/* the main function -------------------------------------------------------*/
int main(void) {
    QF_init(Q_DIM(QF_active)); /* initialize the QF-nano framework */
    BSP_init(); /* initialize the Board Support Package */

    RC5Process_ctor(); /* in C you must explicitly call the Blinky constructor */
    Refresher_ctor();
    return QF_run(); /* transfer control to QF-nano */
}