/*$file${.::rc5process.h} ##################################################*/
/*
* Model: refrsher.qm
* File:  ${.::rc5process.h}
*
* This code has been generated by QM tool (https://state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${.::rc5process.h} ###############################################*/
#ifndef RC5PROCESS_H
#define RC5PROCESS_H

#include"qpn.h"

/* define the event signals used in the application ------------------------*/
enum RC5Signals {
    RC5_DATA_READY_SIG = Q_USER_SIG,
    MAX_SIG /* the last signal */
};

/* active object(s) used in this application -------------------------------*/
extern struct RC5Process AO_RC5Process; /* opaque struct */
/*$declare${AOs::RC5Process_ctor} ##########################################*/
/*${AOs::RC5Process_ctor} ..................................................*/
void RC5Process_ctor(void);
/*$enddecl${AOs::RC5Process_ctor} ##########################################*/

#endif /* RC5PROCESS_H */