/*$file${.::rc5process.c} ##################################################*/
/*
* Model: refrsher.qm
* File:  ${.::rc5process.c}
*
* This code has been generated by QM tool (https://state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${.::rc5process.c} ###############################################*/
#include "qpn.h"    /* QP-nano framework API */
#include "bsp.h"    /* Board Support Package interface */
#include "rc5process.h"
#include "refresher.h"
#include "rc5.h"
#include "lllio.h"

/* ask QM to declare the Blinky class --------------------------------------*/
/*$declare${AOs::RC5Process} ###############################################*/
/*${AOs::RC5Process} .......................................................*/
typedef struct RC5Process {
/* protected: */
    QActive super;
} RC5Process;

/* protected: */
static QState RC5Process_initial(RC5Process * const me);
static QState RC5Process_process_rc5_cmd(RC5Process * const me);
/*$enddecl${AOs::RC5Process} ###############################################*/

/* the single instance of the Blinky active object -------------------------*/
RC5Process AO_RC5Process;

/* ask QM to define the Blinky class ---------------------------------------*/
/*$define${AOs::RC5Process_ctor} ###########################################*/
/* Check for the minimum required QP version */
#if ((QP_VERSION < 601) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8)))
#error qpn version 6.0.1 or higher required
#endif
/*${AOs::RC5Process_ctor} ..................................................*/
void RC5Process_ctor(void) {
    RC5Process * const me = &AO_RC5Process;
    QActive_ctor(&me->super, Q_STATE_CAST(&RC5Process_initial));
}
/*$enddef${AOs::RC5Process_ctor} ###########################################*/
/*$define${AOs::RC5Process} ################################################*/
/*${AOs::RC5Process} .......................................................*/
/*${AOs::RC5Process::SM} ...................................................*/
static QState RC5Process_initial(RC5Process * const me) {
    /*${AOs::RC5Process::SM::initial} */
    return Q_TRAN(&RC5Process_process_rc5_cmd);
}
/*${AOs::RC5Process::SM::process_rc5_cmd} ..................................*/
static QState RC5Process_process_rc5_cmd(RC5Process * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::RC5Process::SM::process_rc5_cmd::RC5_DATA_READY} */
        case RC5_DATA_READY_SIG: {
            int16_t cmd = rc5GetCommand();

            switch(cmd)
            {
              case RC5_CODE_STANDBY: {
                QACTIVE_POST((QActive *)&AO_Refresher, R_STANDBY_SIG, 0U);
                break;
              }
              case RC5_CODE_CHANNEL_UP: {
                QACTIVE_POST((QActive *)&AO_Refresher, R_REFRESH_CMD_SIG, 0U);
                break;
              }
              case RC5_CODE_VOLUME_UP: {
                QACTIVE_POST((QActive *)&AO_Refresher, R_SET_INTERVAL_CMD_SIG, 0U);
                break;
              }
              case RC5_CODE_VOLUME_DOWN: {
                QACTIVE_POST((QActive *)&AO_Refresher, R_SET_INTERVAL_CMD_SIG, 1U);
                break;
              }
              default:{
                break;
              }
            }

            status_ = Q_HANDLED();
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::RC5Process} ################################################*/
