/*$file${.::refresher.c} ###################################################*/
/*
* Model: refrsher.qm
* File:  ${.::refresher.c}
*
* This code has been generated by QM tool (https://state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${.::refresher.c} ################################################*/
#include "qpn.h"    /* QP-nano framework API */
#include "bsp.h"    /* Board Support Package interface */
#include "lllio.h"
#include "refresher.h"

/* ask QM to declare the Blinky class --------------------------------------*/
/*$declare${AOs::Refresher} ################################################*/
/*${AOs::Refresher} ........................................................*/
typedef struct Refresher {
/* protected: */
    QActive super;

/* public: */
    uint16_t time_to_refresh;
} Refresher;

/* protected: */
static QState Refresher_initial(Refresher * const me);
static QState Refresher_on(Refresher * const me);
static QState Refresher_wait(Refresher * const me);
static QState Refresher_refresh(Refresher * const me);
static QState Refresher_set_intervals(Refresher * const me);
static QState Refresher_off(Refresher * const me);
/*$enddecl${AOs::Refresher} ################################################*/

/* the single instance of the Blinky active object -------------------------*/
Refresher AO_Refresher;

/* ask QM to define the Blinky class ---------------------------------------*/
/*$define${AOs::Refresher_ctor} ############################################*/
/* Check for the minimum required QP version */
#if ((QP_VERSION < 601) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8)))
#error qpn version 6.0.1 or higher required
#endif
/*${AOs::Refresher_ctor} ...................................................*/
void Refresher_ctor(void) {
    Refresher * const me = &AO_Refresher;
    QActive_ctor(&me->super, Q_STATE_CAST(&Refresher_initial));
    me->time_to_refresh = 8;
}
/*$enddef${AOs::Refresher_ctor} ############################################*/
/*$define${AOs::Refresher} #################################################*/
/*${AOs::Refresher} ........................................................*/
/*${AOs::Refresher::SM} ....................................................*/
static QState Refresher_initial(Refresher * const me) {
    /*${AOs::Refresher::SM::initial} */
    return Q_TRAN(&Refresher_off);
}
/*${AOs::Refresher::SM::on} ................................................*/
static QState Refresher_on(Refresher * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Refresher::SM::on} */
        case Q_ENTRY_SIG: {
            lllioSetLEDState(GREEN_LED, LED_ON);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Refresher::SM::on} */
        case Q_EXIT_SIG: {
            lllioSetLEDState(GREEN_LED, LED_OFF);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Refresher::SM::on::R_STANDBY} */
        case R_STANDBY_SIG: {
            status_ = Q_TRAN(&Refresher_off);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*${AOs::Refresher::SM::on::wait} ..........................................*/
static QState Refresher_wait(Refresher * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Refresher::SM::on::wait} */
        case Q_ENTRY_SIG: {
            QActive_armX((QActive *)me, 1U, ((me->time_to_refresh)*8000), 0);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Refresher::SM::on::wait} */
        case Q_EXIT_SIG: {
            QActive_disarmX((QActive *)me, 1U);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Refresher::SM::on::wait::R_REFRESH_CMD} */
        case R_REFRESH_CMD_SIG: {
            status_ = Q_TRAN(&Refresher_refresh);
            break;
        }
        /*${AOs::Refresher::SM::on::wait::R_SET_INTERVAL_CMD} */
        case R_SET_INTERVAL_CMD_SIG: {
            status_ = Q_TRAN(&Refresher_set_intervals);
            break;
        }
        /*${AOs::Refresher::SM::on::wait::Q_TIMEOUT1} */
        case Q_TIMEOUT1_SIG: {
            status_ = Q_TRAN(&Refresher_refresh);
            break;
        }
        default: {
            status_ = Q_SUPER(&Refresher_on);
            break;
        }
    }
    return status_;
}
/*${AOs::Refresher::SM::on::refresh} .......................................*/
static QState Refresher_refresh(Refresher * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Refresher::SM::on::refresh} */
        case Q_ENTRY_SIG: {
            lllioRefresherOn();
            QActive_armX((QActive *)me, 0U, 500U, 0);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Refresher::SM::on::refresh} */
        case Q_EXIT_SIG: {
            lllioRefresherOff();
            QActive_disarmX((QActive *)me, 0U);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Refresher::SM::on::refresh::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            status_ = Q_TRAN(&Refresher_wait);
            break;
        }
        default: {
            status_ = Q_SUPER(&Refresher_on);
            break;
        }
    }
    return status_;
}
/*${AOs::Refresher::SM::on::set_intervals} .................................*/
static QState Refresher_set_intervals(Refresher * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Refresher::SM::on::set_intervals} */
        case Q_ENTRY_SIG: {
            //lllioSetLEDState(RED_LED, LED_ON);
            lllioToggleRedLed();
            QActive_armX((QActive *)me, 0U, 1000U, 0);

            if(0 == Q_PAR(me))
            {
              if(me->time_to_refresh < 8) {
                me->time_to_refresh++;
              }
              //  lllioToggleRedLed();
            }
            else if(1 == Q_PAR(me))
            {
              if(me->time_to_refresh > 1) {
                me->time_to_refresh--;
              }
                //lllioToggleRedLed();
            }
            else
            {
            }
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Refresher::SM::on::set_intervals} */
        case Q_EXIT_SIG: {

            QActive_disarmX((QActive *)me, 0U);
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Refresher::SM::on::set_intervals::Q_TIMEOUT} */
        case Q_TIMEOUT_SIG: {
            lllioSetLEDState(RED_LED, LED_OFF);
            status_ = Q_TRAN(&Refresher_refresh);
            break;
        }
        /*${AOs::Refresher::SM::on::set_intervals::R_SET_INTERVAL_CMD} */
        case R_SET_INTERVAL_CMD_SIG: {
            status_ = Q_TRAN(&Refresher_set_intervals);
            break;
        }
        default: {
            status_ = Q_SUPER(&Refresher_on);
            break;
        }
    }
    return status_;
}
/*${AOs::Refresher::SM::off} ...............................................*/
static QState Refresher_off(Refresher * const me) {
    QState status_;
    switch (Q_SIG(me)) {
        /*${AOs::Refresher::SM::off::R_STANDBY} */
        case R_STANDBY_SIG: {
            status_ = Q_TRAN(&Refresher_wait);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::Refresher} #################################################*/
